# -*- coding: utf-8 -*-
"""
/***************************************************************************
 netcom_bw_export
                                 A QGIS plugin
 netcom_bw_export
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-28
        copyright            : (C) 2025 by Darko Nedic
        email                : nedic.darko@geodigit.rs
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load netcom_bw_export class from file netcom_bw_export.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .netcom_bw_export import netcom_bw_export
    return netcom_bw_export(iface)
