# -*- coding: utf-8 -*-
"""
/***************************************************************************
 netcom_bw_exportDialog
                                 A QGIS plugin
 netcom_bw_export
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-11-28
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Darko Nedic
        email                : nedic.darko@geodigit.rs
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.PyQt.QtCore import Qt
from qgis.core import QgsProject, QgsVectorLayer, QgsWkbTypes

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'netcom_bw_export_dialog_base.ui'))


class netcom_bw_exportDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(netcom_bw_exportDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Connect Export button
        self.button_export.clicked.connect(self.on_export_clicked)
        
        self.selected_folder = None
    
    def on_export_clicked(self):
        """Handle Export button click - open folder selection dialog"""
        folder = QtWidgets.QFileDialog.getExistingDirectory(
            self,
            "Select Output Folder",
            os.path.expanduser('~'),
            QtWidgets.QFileDialog.ShowDirsOnly
        )
        
        if folder:
            self.selected_folder = folder
            self.accept()  # Close dialog and return success
    
    def get_job_id(self):
        """Get the job_id value from the ComboBox"""
        return self.comboBox_job.currentData()
    
    def get_output_folder(self):
        """Get the selected output folder"""
        return self.selected_folder
